// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDki7iIAdA9CmFSiGrFWIjHpGbM-1mYS4Q',
    appId: '1:344596498444:web:01fd8e8d79900ada59c629',
    messagingSenderId: '344596498444',
    projectId: 'tripsnap-7b236',
    authDomain: 'tripsnap-7b236.firebaseapp.com',
    storageBucket: 'tripsnap-7b236.firebasestorage.app',
    measurementId: 'G-9WFY7CD8SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGqcIIe-t0iafTiyoKI3VCBwZQxeR9lqQ',
    appId: '1:344596498444:android:9d1c9548093124bf59c629',
    messagingSenderId: '344596498444',
    projectId: 'tripsnap-7b236',
    storageBucket: 'tripsnap-7b236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKCEWmrp1O5pOqlZDF4m1pXQVpL0rh4iE',
    appId: '1:344596498444:ios:0e680f45dac6459459c629',
    messagingSenderId: '344596498444',
    projectId: 'tripsnap-7b236',
    storageBucket: 'tripsnap-7b236.firebasestorage.app',
    iosBundleId: 'com.example.tripsnapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKCEWmrp1O5pOqlZDF4m1pXQVpL0rh4iE',
    appId: '1:344596498444:ios:0e680f45dac6459459c629',
    messagingSenderId: '344596498444',
    projectId: 'tripsnap-7b236',
    storageBucket: 'tripsnap-7b236.firebasestorage.app',
    iosBundleId: 'com.example.tripsnapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDki7iIAdA9CmFSiGrFWIjHpGbM-1mYS4Q',
    appId: '1:344596498444:web:217db12f825a5e2c59c629',
    messagingSenderId: '344596498444',
    projectId: 'tripsnap-7b236',
    authDomain: 'tripsnap-7b236.firebaseapp.com',
    storageBucket: 'tripsnap-7b236.firebasestorage.app',
    measurementId: 'G-SQH3SBMQMT',
  );
}
